name: 'Terraform GitHub Actions'
on:
  - pull_request

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Terraform Format'
        uses: clouddrove/github-actions@v1.0
        with:
          actions_subcommand: 'fmt'

      - name: 'Terraform Init'
        uses: clouddrove/github-actions@v1.0
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example

      - name: 'Terratest'
        uses: clouddrove/github-actions@v1.0
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: ./_test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
